### ISSUE TITLE
Disable Email Authentication

### ISSUE THREAD

**Issue by ph03n1x9000** [XLRstats/xlrstats-web-v3#52]
Hi,

I just wanted to know if there is a way we can stop XLRstats from having to email users with new registration for activation. It is set up on a server without mail capabilities.

Also, how can we edit the footer? There are dead links there under "Community" named "Our Community Site", "Our Forums" and "Our Matches".

**Comment by markweirath** [comment]
1.) No, you'll need email functionality. But you can set an external smtp email account in /app/Config/email.php

2.) https://github.com/XLRstats/xlrstats-web-v3/blob/a14bbfc17323495186fe5bee2422b7928d20aa9a/app/View/Layouts/default.ctp#L178-L180
