### ISSUE TITLE
XLR Stats Site not working anymore

### ISSUE THREAD

**Issue by CCStyleCC** [XLRstats/xlrstats-web-v3#53]
Good Evening.

I am running the XLR Stats Programm since one month without any problems on my server. Today I saw its not working anymore..

the link is http://master.collegeclan.de/xlrstats

The Error I get are:
Warning (2): file_get_contents(http://xlr8or.snt.utwente.nl/xlrstats/license_server/licenses/check): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
 [APP/Controller/Component/XlrFunctionsComponent.php, line 245]

Warning (2): Cannot modify header information - headers already sent by (output started at /var/www/xlrstats/lib/Cake/Utility/Debugger.php:802) [CORE/Cake/Network/CakeResponse.php, line 443]

I never changed anything in the last month and today.
What I did today is refreshing the Website. I also downloaded XLR again and reinstalled it.
Still getting the same error.
I have a legit license wich got sent to my by mail.

I need help. 

CC' Style

**Comment by markweirath** [comment]
These are not php-errors, but warnings.

pls. request a new license, the license database is cleaned up every now and then... your license request might not have been seen by the license server for a certain amount of time hence the removal.

**Comment by CCStyleCC** [comment]
I did alredy yesterday. The Problem is sill there.

**Comment by CCStyleCC** [comment]
Can it be possible that the Problem got right now fixed? Cuz the error is away.

**Comment by CCStyleCC** [comment]
XLR Stats works again for me. 
I dont know if you did something. I did not. But its working again.
