### ISSUE TITLE
XlrFunctionsComponent error

### ISSUE THREAD

**Issue by Anaphi** [XLRstats/xlrstats-web-v3#54]
Issue appeared 36 hours ago without any modification on server.

\app\Controller\Component\XlrFunctionsComponent.php (line 233)
'CURLINFO_HTTP_CODE: 100'

Seems to be linked with license control .. 

I do not understand.

**Comment by ozguruysal** [comment]
This is probably related with issue #53.

**Comment by Anaphi** [comment]
Issue suddenly vanished.

Looks link it could be due to a call to an external URL ?
