### ISSUE TITLE
Players come up as they all in Spectator Team while actually playing in Teams

### ISSUE THREAD

**Issue by CCStyleCC** [XLRstats/xlrstats-web-v3#55]
I have again a issue.

http://master.collegeclan.de/xlrstats/6/server_players

When you look there you will see the players are all in the Spectator Team.
But when I look to the Server they all are playing correct.

Xlr Stats issue or issue with B3 ? Cuz the website take it out of the Status plugin B3.

**Comment by ozguruysal** [comment]
You're right. This one seems to be B3 issue rather than XLRstats webfront. Please ask in [B3 forums](http://forum.bigbrotherbot.net/).

**Comment by CCStyleCC** [comment]
Thank you. I will look there then. =)
